version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node-app
    container_name: seguradora_app
    volumes:
      - api_volume_files:/usr/src/app/storage:rw
    ports:
      - 3000:3000
    depends_on:
     - mysqldb
    networks:
      - seguradora_net

  mysqldb:
    image: mysql:8.0.21
    container_name: mysqldb
    env_file:
      - .env
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - api_volume_db:/var/lib/mysql
      - ./my_conf.cnf:/etc/mysql/conf.d/my_conf.cnf:ro
    networks:
      - seguradora_net
    restart: always

networks:
  seguradora_net:
    driver: bridge

volumes:
  api_volume_db: {}
  api_volume_files: {}
  api_volume_logs: {}
