-- CreateTable
CREATE TABLE `apolice` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOLICE_TIPO_ID` INTEGER NOT NULL,
    `NUMERO` VARCHAR(64) NULL,
    `SEGURADO_ID` INTEGER NOT NULL,
    `DATA_INICIO` DATE NULL,
    `DATA_FIM` DATE NULL,
    `APOLICE_FRACIONAMENTO_ID` INTEGER NOT NULL,
    `APOLICE_ESTADO_ID` INTEGER NOT NULL,
    `VALOR_PREMIO` DECIMAL(13, 2) NULL,
    `INSERIDO_POR` INTEGER NULL,
    `ACTUALIZADO_POR` INTEGER NULL,
    `REMOVIDO_POR` INTEGER NULL,
    `DATA_INSERCAO` TIMESTAMP(0) NULL,
    `DATA_ACTUALIZACAO` TIMESTAMP(0) NULL,
    `DATA_REMOCAO` TIMESTAMP(0) NULL,

    INDEX `FKAPOLICE218101`(`APOLICE_ESTADO_ID`),
    INDEX `FKAPOLICE395825`(`SEGURADO_ID`),
    INDEX `FKAPOLICE49224`(`APOLICE_TIPO_ID`),
    INDEX `FKAPOLICE599017`(`APOLICE_FRACIONAMENTO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_cobertura` (
    `ID` INTEGER NOT NULL,
    `APOLICE_ID` INTEGER NULL,
    `COBERTURA_ID` INTEGER NULL,
    `VALOR_PAGO` DECIMAL(13, 2) NULL,
    `DESCONTO_EFEC` DECIMAL(13, 2) NULL,

    INDEX `FKAPOLICECOBERT_idx`(`APOLICE_ID`),
    INDEX `FKCOBERTCOBERT_idx`(`COBERTURA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_estado` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NULL,
    `DESCRICAO` VARCHAR(255) NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_fracionamento` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FRACIONADO_EM` VARCHAR(10) NULL,
    `NO_FRACOES` INTEGER NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_historico` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOLICE_ID` INTEGER NOT NULL,
    `APOLICE_TIPO_ID` INTEGER NOT NULL,
    `APOLICE_ESTADO_ID` INTEGER NOT NULL,
    `ACCAO` VARCHAR(255) NULL,
    `DATA` INTEGER NULL,
    `AUTOR_ACCAO` INTEGER NULL,

    INDEX `FKAPOLICE_HI457370`(`APOLICE_ESTADO_ID`),
    INDEX `FKAPOLICE_HI724695`(`APOLICE_TIPO_ID`),
    INDEX `FKAPOLICE_HI851163`(`APOLICE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_item_segurado` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOLICE_TIPO_ID` INTEGER NOT NULL,
    `ITEM_ID` INTEGER NOT NULL,
    `APOLICE_ID` INTEGER NOT NULL,

    INDEX `FKAPOLICE_IT272194`(`APOLICE_TIPO_ID`),
    INDEX `FKAPOLICE_IT332390`(`ITEM_ID`),
    INDEX `FKAPOLICE_IT332490_idx`(`APOLICE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_pagamento` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOLICE_ID` INTEGER NOT NULL,
    `DESCONTOS` DECIMAL(13, 2) NULL,
    `VALOR_PAGO` DECIMAL(13, 2) NULL,
    `DATA_INSERCAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` TIMESTAMP(0) NULL,
    `DATA_REMOCAO` TIMESTAMP(0) NULL,

    INDEX `FKAPOLICE_PA210466`(`APOLICE_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_tipo` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SIGLA` VARCHAR(30) NULL,
    `NOME` VARCHAR(255) NULL,
    `DESCRICAO` MEDIUMTEXT NULL,
    `INSERIDO_POR` INTEGER NULL,
    `ACTUALIZADO_POR` INTEGER NULL,
    `REMOVIDO_POR` INTEGER NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `SIGLA`(`SIGLA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `apolice_tomador` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TOMADOR_ID` INTEGER NOT NULL,
    `APOLICE_ID` INTEGER NOT NULL,
    `DATA_INSERCAO` TIMESTAMP(0) NULL,
    `DATA_ACTUALIZACAO` TIMESTAMP(0) NULL,
    `DATA_REMOCAO` TIMESTAMP(0) NULL,

    INDEX `FKAPOLICE_TO613390`(`APOLICE_ID`),
    INDEX `FKAPOLICE_TO64820`(`TOMADOR_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cobertura` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOLICE_TIPO_ID` INTEGER NOT NULL,
    `COBERTURA_BASE` BIT(1) NULL DEFAULT b'0',
    `SIGLA` VARCHAR(30) NULL,
    `NOME` VARCHAR(255) NULL,
    `DESCRICAO` LONGTEXT NULL,
    `INSERIDO_POR` INTEGER NULL,
    `ACTUALIZADO_POR` INTEGER NULL,
    `REMOVIDO_POR` INTEGER NULL,
    `VALOR_PAGAR` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `DESCONTO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `SIGLA`(`SIGLA`),
    INDEX `FKAPOLICE_CO255895`(`APOLICE_TIPO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `new_table` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` ENUM('Alto', 'Medio', 'Baixo') NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pessoa` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PESSOA_TIPO_ID` INTEGER NOT NULL,
    `NOME` VARCHAR(255) NULL,
    `DATA_NASCIMENTO` DATE NULL,
    `SEXO` VARCHAR(1) NULL,
    `NBI` VARCHAR(64) NULL,
    `NIF` VARCHAR(64) NULL,
    `ESTADO_CIVIL` VARCHAR(1) NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `NBI`(`NBI`),
    UNIQUE INDEX `NIF`(`NIF`),
    INDEX `FKPESSOA892258`(`PESSOA_TIPO_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pessoa_endereco` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PESSOA_ID` INTEGER NOT NULL,
    `TELEFONE` VARCHAR(80) NULL,
    `TELEFONE_ALTERNATIVO` VARCHAR(80) NULL,
    `EMAIL` VARCHAR(100) NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `TELEFONE`(`TELEFONE`),
    UNIQUE INDEX `EMAIL`(`EMAIL`),
    INDEX `FKPESSOA_END360638`(`PESSOA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pessoa_tipo` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME_TIPO` VARCHAR(255) NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `preco_cilindrada` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NULL,
    `LOTACAO` INTEGER NULL,
    `VEICULO_CATEGORIA_ID` INTEGER NOT NULL,
    `PREMIO_TRIMESTRAL` DECIMAL(13, 2) NULL,
    `PREMIO_SEMESTRAL` DECIMAL(13, 2) NULL,
    `PREMIO_ANUAL` DECIMAL(13, 2) NULL,
    `PESO_KG` INTEGER NULL,
    `CILINDRADA_MIN` INTEGER NULL,
    `CILINDRADA_MAX` INTEGER NULL,
    `INSERIDO_POR` INTEGER NULL,
    `ACTUALIZADO_POR` INTEGER NULL,
    `DATA_CRIACAO` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `DATA_ACTUALIZACAO` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FKPRECO_CILI487359`(`VEICULO_CATEGORIA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `veiculo` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `VEICULO_CATEGORIA_ID` INTEGER NOT NULL,
    `MATRICULA` VARCHAR(24) NULL,
    `MARCA` VARCHAR(255) NULL,
    `MODELO` VARCHAR(255) NULL,
    `ANO_AQUISICAO` INTEGER NULL,
    `CAPITAL_AQUISICAO` DECIMAL(13, 2) NULL,
    `PESO_BRUTO` INTEGER NULL,
    `N_LOTACAO` INTEGER NULL,
    `ANO_FABRICO` INTEGER NULL,
    `CILINDRADA` INTEGER NULL,
    `REF_CHASSI` VARCHAR(64) NULL,
    `DESCRICAO` VARCHAR(4000) NULL,
    `INSERIDO_POR` INTEGER NULL,
    `ACTUALIZADO_POR` INTEGER NULL,
    `REMOVIDO_POR` INTEGER NULL,
    `DATA_INSERCAO` TIMESTAMP(0) NULL,
    `DATA_ACTUALIZACAO` TIMESTAMP(0) NULL,
    `DATA_REMOCAO` TIMESTAMP(0) NULL,

    UNIQUE INDEX `MATRICULA`(`MATRICULA`),
    INDEX `FKVEICULO357677`(`VEICULO_CATEGORIA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `veiculo_categoria` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NULL,
    `REMOVIDO_POR` INTEGER NULL,
    `DATA_INSERCAO` TIMESTAMP(0) NULL,
    `DATA_ACTUALIZACAO` TIMESTAMP(0) NULL,
    `DATA_REMOCAO` TIMESTAMP(0) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ficheiro` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(255) NOT NULL,
    `SIZE` INTEGER NOT NULL,
    `PATH` VARCHAR(255) NULL,
    `EXT` VARCHAR(255) NOT NULL,
    `CONTENT` TEXT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `apolice` ADD CONSTRAINT `FKAPOLICE218101` FOREIGN KEY (`APOLICE_ESTADO_ID`) REFERENCES `apolice_estado`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice` ADD CONSTRAINT `FKAPOLICE395825` FOREIGN KEY (`SEGURADO_ID`) REFERENCES `pessoa`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice` ADD CONSTRAINT `FKAPOLICE49224` FOREIGN KEY (`APOLICE_TIPO_ID`) REFERENCES `apolice_tipo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice` ADD CONSTRAINT `FKAPOLICE599017` FOREIGN KEY (`APOLICE_FRACIONAMENTO_ID`) REFERENCES `apolice_fracionamento`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_cobertura` ADD CONSTRAINT `FKAPOLICECOBERT` FOREIGN KEY (`APOLICE_ID`) REFERENCES `apolice`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_cobertura` ADD CONSTRAINT `FKCOBERTCOBERT` FOREIGN KEY (`COBERTURA_ID`) REFERENCES `cobertura`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_historico` ADD CONSTRAINT `FKAPOLICE_HI457370` FOREIGN KEY (`APOLICE_ESTADO_ID`) REFERENCES `apolice_estado`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_historico` ADD CONSTRAINT `FKAPOLICE_HI724695` FOREIGN KEY (`APOLICE_TIPO_ID`) REFERENCES `apolice_tipo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_historico` ADD CONSTRAINT `FKAPOLICE_HI851163` FOREIGN KEY (`APOLICE_ID`) REFERENCES `apolice`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_item_segurado` ADD CONSTRAINT `FKAPOLICE_IT272194` FOREIGN KEY (`APOLICE_TIPO_ID`) REFERENCES `apolice_tipo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_item_segurado` ADD CONSTRAINT `FKAPOLICE_IT332390` FOREIGN KEY (`ITEM_ID`) REFERENCES `veiculo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_item_segurado` ADD CONSTRAINT `FKAPOLICE_IT332490` FOREIGN KEY (`APOLICE_ID`) REFERENCES `apolice`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_pagamento` ADD CONSTRAINT `FKAPOLICE_PA210466` FOREIGN KEY (`APOLICE_ID`) REFERENCES `apolice`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_tomador` ADD CONSTRAINT `FKAPOLICE_TO613390` FOREIGN KEY (`APOLICE_ID`) REFERENCES `apolice`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `apolice_tomador` ADD CONSTRAINT `FKAPOLICE_TO64820` FOREIGN KEY (`TOMADOR_ID`) REFERENCES `pessoa`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `cobertura` ADD CONSTRAINT `FKAPOLICE_CO255895` FOREIGN KEY (`APOLICE_TIPO_ID`) REFERENCES `apolice_tipo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `pessoa` ADD CONSTRAINT `FKPESSOA892258` FOREIGN KEY (`PESSOA_TIPO_ID`) REFERENCES `pessoa_tipo`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `pessoa_endereco` ADD CONSTRAINT `FKPESSOA_END360638` FOREIGN KEY (`PESSOA_ID`) REFERENCES `pessoa`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `preco_cilindrada` ADD CONSTRAINT `FKPRECO_CILI487359` FOREIGN KEY (`VEICULO_CATEGORIA_ID`) REFERENCES `veiculo_categoria`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `veiculo` ADD CONSTRAINT `FKVEICULO357677` FOREIGN KEY (`VEICULO_CATEGORIA_ID`) REFERENCES `veiculo_categoria`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
