CREATE DEFINER=`root`@`localhost` TRIGGER `adenda_BEFORE_INSERT` BEFORE INSERT ON `adenda` FOR EACH ROW BEGIN
    SET NEW.NUMERO = CONCAT('1 80 ', YEAR(NOW()), '/', LPAD((SELECT IFNULL(MAX(SUBSTRING_INDEX(NUMERO, '/', -1)), 0) + 1 FROM adenda), 4, '0'));

END