CREATE DEFINER=`root`@`localhost` TRIGGER `apolice_BEFORE_INSERT` BEFORE INSERT ON `apolice` FOR EACH ROW BEGIN
    SET NEW.NUMERO = CONCAT('1 90 ', YEAR(NOW()), '/', LPAD((SELECT IFNULL(MAX(SUBSTRING_INDEX(NUMERO, '/', -1)), 0) + 1 FROM apolice), 4, '0'));
END