SELECT * FROM giant_db.pessoa_tipo;
ALTER TABLE giant_db.pessoa_tipo
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

INSERT INTO giant_db.pessoa_tipo(NOME_TIPO) VALUES ('Pessoa Física'), ('Pessoa Jirídica')

ALTER TABLE giant_db.pessoa
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

INSERT INTO giant_db.pessoa(PESSOA_TIPO_ID, NOME, DATA_NASCIMENTO, SEXO, NBI, NIF, ESTADO_CIVIL) 
VALUES( 1, 'Andre Marcos', '1990-11-16', 'M', '73365384565', '43766465', 'S'), ( 1, 'Semir Marcos', '1959-11-16', 'M', '73365354505', '4378865', 'S');

INSERT INTO giant_db.pessoa_endereco(PESSOA_ID, TELEFONE, TELEFONE_ALTERNATIVO, EMAIL) 
VALUES( LAST_INSERT_ID(),'989884938','988989943','am@giant.ao');

ALTER TABLE giant_db.pessoa_endereco
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

SELECT * FROM pessoa 
INNER JOIN pessoa_endereco ON 
pessoa.ID=pessoa_endereco.PESSOA_ID 
INNER JOIN pessoa_tipo ON
pessoa.PESSOA_TIPO_ID = pessoa_tipo.ID

ALTER TABLE giant_db.preco_cilindrada
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        
ALTER TABLE giant_db.apolice_tipo
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

ALTER TABLE giant_db.apolice_cobertura
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


ALTER TABLE giant_db.apolice_estado
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

ALTER TABLE giant_db.apolice_fracionamento
ADD COLUMN DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DATA_ACTUALIZACAO DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP



        