SELECT * FROM giant_db.apolice_cobertura;

INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES ('1', b'1', b'RTER', b'Responsabilidade civil perante terceiros', b'A pessoa responderá por ato causado por terceiro, sendo para tanto necessário que exista um vínculo jurídico entre o responsável e o causador do dano. Em regra, tal responsabilidade gera responsabilidade solidária, com algumas exceções, como o caso do incapaz que responde subsidiariamente. ');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'RFAC', b'Responsabilidade Civil Facultativa', b'A cobertura de responsabilidade civil facultativa veicular (RCF-V) pode ser entendida, de forma simples, como aquela que cobre danos causados a terceiros. Inclui acidentes de trânsito, atropelamentos, batidas, entre outros. Você está dirigindo e as crianças pedem pra colocar música, por exemplo.');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'CHOQ', b'Choque', b'O choque é um tipo de acidente em que o veículo em movimento choca-se contra um obstáculo fixo, que pode ser um muro, uma cerca, um poste, um ou mais veículos parados, meio fio, canteiro, ilha de segurança ou qualquer outro, inclusive casas');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'CCAP', b'Colisão e Capotamento', b'Esta cobertura garante, até ao valor do capital seguro indicado nas Condições Particulares, o ressarcimento dos danos causados ao Veículo Seguro em virtude de choque (embate do veículo contra qualquer corpo fixo, ou sofrido por aquele quando imobilizado), colisão (embate do veículo com qualquer outro corpo em movimento), ou capotamento (acidente em que o veículo perca a sua posição normal e não resulte de Choque ou Colisão.)');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'FROB', b'Furto ou Roubo', b'Danos derivados pelo desaparecimento, destruição ou deterioração do veículo por motivo de Furto e Roubo.Para que esta cobertura funcione terá sempre que participar às autoridades policiais o sucedido e solicitar o auto de ocorrência. Em caso de desaparecimento da viatura, o Segurador só o indemnizará se passados 60 dias da data de participação do Furto e Roubo, o veículo não tiver sido encontrado.  ');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'INCE', b'Incêndio', b'Esta cobertura garante ao Segurado o ressarcimento dos danos que resultem para o veículo seguro em consequência de Incêndio, Raio e Explosão, quer aquele se encontre em marcha ou parado, recolhido em garagem ou em qualquer outro local. ');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'RINC', b'Raio ou Explosão', b'Esta cobertura garante ao Segurado o ressarcimento dos danos que resultem para o veículo seguro em consequência de Incêndio, Raio e Explosão, quer aquele se encontre em marcha ou parado, recolhido em garagem ou em qualquer outro local. ');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'QISV', b'Quebra Isolada de Vidros', b'Incluem-se danos, em virtude de quebra isolada dos vidros, para-brisas, óculo traseiro e vidros laterais, causados por causa não compreendida, em qualquer outra cobertura. ');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`, `DESCRICAO`) VALUES (b'1', b'0', b'FNAT', b'Fenómenos da Natureza', b'- Ação de greves, tumultos, motins e alterações da ordem pública;- Atos de vandalismo, terrorismo e sabotagem;- Ação direta de trombas de água, chuvas torrenciais, enxurradas e aluimento de terras;');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`) VALUES (b'1', b'0', b'GREV', b'Greves');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`) VALUES (b'1', b'0', b'TUOP', b'Tumultos e Alterações da Ordem Pública');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`) VALUES (b'1', b'0', b'PUSO', b'Privação de Uso');
INSERT INTO `giant_db`.`apolice_cobertura` (`APOLICE_TIPO_ID`, `COBERTURA_BASE`, `SIGLA`, `NOME`) VALUES (b'1', b'0', b'OCPV', b'Ocupantes da Viatura');
